---
- name: apt update
  apt: update_cache=yes cache_valid_time=3600

- name: install packages
  apt: name={{ item }} state=present
  with_items:
    - libqt4-dev
    - g++
    - make
    - libzip-dev
